### ISSUE TITLE
Filename

### ISSUE THREAD

**Issue by abstractFlo** [maximilianschmitt/ng-autobootstrap#5]
Hi Maximillian,

is there a way to change the file name convention to fileName ? i hope you can help

Kind regards and good work

**Comment by maximilianschmitt** [comment]
Hey Flo, casing is detected automatically, so what you are requesting should work out-of-the-box! Also have a look at this: https://github.com/maximilianschmitt/ng-autobootstrap#default-options

Let me know if you have any more questions!

**Comment by maximilianschmitt** [comment]
I'll be closing this issue. If you still have problems with this, feel free to re-open.
